name: null
favicon: null
layout_spectrum: 0.8671238897368312
typography_spectrum: 0.2477846359834075
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.877323237946257
  lightness: 0.4359240017365664
  saturation: 0.7373882823158056
  rhythmicContrast: 0.5751085563097149
purpose: []
